language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
env:
  - POSTGRES_USER=postgres

branches:
  only:
    - master
    - /^feature-.*$/

before_script:
  - psql -U $POSTGRES_USER -c 'create database meetinglibs_test;'

script:
  - bundle exec rake db:schema:load db:test:prepare
  - bundle exec rspec
  - bundle exec guard-jasmine
