---
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3

env:
  global:
    - secure: "aZ0L5QyCYQUTA75lN0nRbSk9yuac9Ul+83h2nMHMQeCkkEyZjr+JpgYsQ2J3\nRgRfM+CdlKfSbiUurd7lZ6S+U7QCsSCiJF73FEPUHumzQL+XtT6nNKHNObK/\newjM/tBoZCgm/POdMaKXN+XPVAdXYcJORdpqlvd27NhWOHACndU="
    - POSTGRES_USER=postgres

branches:
  only:
    - master
    - /^feature-.*$/

before_script:
  - psql -U $POSTGRES_USER -c 'create database meetinglibs_test;'

script:
  - bundle exec rake db:migrate db:test:prepare
  - bundle exec rspec
  - bundle exec guard-jasmine
