---
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3

env:
  global:
    - secret: 'GtXGVAIHLAuH4CAq+fb/zSBuF7oO96stPfU0R81WEW47kwZ6A7G4xJPREU+O\nPsik1tEjUUY2T+m6rrEe7QOfMuoMMjIFnemSYlKzH/fBmvahvpkvNOgvtFuS\nLgyCLXcwnnSGzJvGmKBZSZ0zHP8FElpAiIo14eH/unOBoO4tlgo='
    - POSTGRES_USER=postgres

branches:
  only:
    - master
    - /^feature-.*$/

before_script:
  - psql -U $POSTGRES_USER -c 'create database meetinglibs_test;'

script:
  - bundle exec rake db:migrate db:test:prepare
  - bundle exec rspec
  - bundle exec guard-jasmine
