---
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3

env:
  global:
    - secret: "fgZ62h8S4snfyLUOXurKuYgoQsJQdU9x3G8UVjdvr1AVp5RJVQTMIi333m4y\nrX03lvBsaatksTa8RNu+UUacaoJcomy940+6DTIl1dawXt2R9Per6/zJh3Im\nuUjJSrEgz6Gj9xie0E8DnxBWx7whbGW1r+mwR3dpcfiv7szEsxU="
    - POSTGRES_USER=postgres

branches:
  only:
    - master
    - /^feature-.*$/

before_script:
  - psql -U $POSTGRES_USER -c 'create database meetinglibs_test;'

script:
  - bundle exec rake db:migrate db:test:prepare
  - bundle exec rspec
  - bundle exec guard-jasmine
