development:
  adapter: postgresql
  encoding: unicode
  database: meetinglibs_development
  pool: 5
  username: <%= Etc.getpwuid(Process.uid).name %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meetinglibs_test
  pool: 5
  username: <%= Etc.getpwuid(Process.uid).name %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: meetinglibs
  pool: 5
  username: meetinglibs
  password:
